spring.application.name=app-nutricionista

spring.datasource.url=jdbc:postgresql://localhost:5432/appnutricionista
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.deserialization.fail-on-null-for-primitives=false

